# Generated by Django 4.1.7 on 2023-03-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasks',
            table='Tasks',
        ),
    ]
