# Generated by Django 4.1.7 on 2023-03-25 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
